// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa7BT21BLo4K1g9UUAbgofJE0N3mivpZI',
    appId: '1:874619078267:web:aa3ee417af831243c644de',
    messagingSenderId: '874619078267',
    projectId: 'test2-a1f71',
    authDomain: 'test2-a1f71.firebaseapp.com',
    storageBucket: 'test2-a1f71.firebasestorage.app',
    measurementId: 'G-S8YEZK1TNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApOzM_ls394nMAV_XMNlR0-J4YDKqJgSg',
    appId: '1:874619078267:android:164516f64dfe1200c644de',
    messagingSenderId: '874619078267',
    projectId: 'test2-a1f71',
    storageBucket: 'test2-a1f71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv8r0_nBjwr4N6ZmZ1T3auX3wQCiRd4zM',
    appId: '1:874619078267:ios:627d4a4aec9544bfc644de',
    messagingSenderId: '874619078267',
    projectId: 'test2-a1f71',
    storageBucket: 'test2-a1f71.firebasestorage.app',
    iosBundleId: 'com.example.ecomart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv8r0_nBjwr4N6ZmZ1T3auX3wQCiRd4zM',
    appId: '1:874619078267:ios:627d4a4aec9544bfc644de',
    messagingSenderId: '874619078267',
    projectId: 'test2-a1f71',
    storageBucket: 'test2-a1f71.firebasestorage.app',
    iosBundleId: 'com.example.ecomart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa7BT21BLo4K1g9UUAbgofJE0N3mivpZI',
    appId: '1:874619078267:web:c4a349a689ce3f9ac644de',
    messagingSenderId: '874619078267',
    projectId: 'test2-a1f71',
    authDomain: 'test2-a1f71.firebaseapp.com',
    storageBucket: 'test2-a1f71.firebasestorage.app',
    measurementId: 'G-L23RYJ8XYD',
  );
}
